# This config file for Travis CI
sudo: required
dist: trusty
language: generic

services:
  - docker

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=dependencies.rosinstall
    - ROS_REPO=ros
    - NOT_TEST_INSTALL=true
    - CMAKE_ARGS=-DENABLE_TESTS=ON
    - ROSDEP_SKIP_KEYS="bullet3 fcl benchmark"
    - BUILD_PKGS_WHITELIST="pcs_detection pcs_msgs pcs_ros pcs_scan_integration"

matrix:
  include:
    - env: ROS_DISTRO=melodic CLANG_FORMAT_CHECK=file CLANG_FORMAT_VERSION=8
      git:
        submodules: false
    - env: ROS_DISTRO=kinetic
    - env: ROS_DISTRO=melodic ROS_PARALLEL_JOBS=-j2 CATKIN_PARALLEL_JOBS=-p2 # Travis was running out of resources and hanging for melodic builds
    - env: ROS_DISTRO=noetic ROS_PARALLEL_JOBS=-j2 CATKIN_PARALLEL_JOBS=-p2
  allow_failures:
    - env: ROS_DISTRO=melodic ROS_REPO=ros-shadow-fixed ROS_PARALLEL_JOBS=-j2 CATKIN_PARALLEL_JOBS=-p3
    - env: ROS_DISTRO=noetic ROS_REPO=ros-shadow-fixed ROS_PARALLEL_JOBS=-j2 CATKIN_PARALLEL_JOBS=-p3

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b legacy

script:
  - .industrial_ci/travis.sh
