#!/usr/bin/env python

import rospy
from cv_bridge import CvBridge
import numpy as np

from pcs_msgs.srv import *
from pcs_detection.histogram_backprojection import HistogramBackprojection


if __name__ == '__main__':
    rospy.init_node('histogram_backprojection_node')
    rospy.spin()
